### ISSUE TITLE
Cannot read property 'SpeechToText' of undefined

### ISSUE THREAD

**Issue by andaralex** [CognitiveBuild/WatsonSpeechPlugin#1]
We try to use this plugin in Cordova application. While running in both browser and Android devices, we got this below error.

ionic.bundle.min.js:150 TypeError: Cannot read property 'SpeechToText' of undefined
    at m.$scope.Speech (controllers.js:279)
    at m.$scope.speech_menu (controllers.js:259)
    at fn (eval at compile (ionic.bundle.min.js:260), <anonymous>:4:229)
    at ionic.bundle.min.js:472
    at m.$eval (ionic.bundle.min.js:176)
    at m.$apply (ionic.bundle.min.js:177)
    at HTMLButtonElement.<anonymous> (ionic.bundle.min.js:472)
    at Pf (ionic.bundle.min.js:70)
    at HTMLButtonElement.d (ionic.bundle.min.js:70)
    at n (ionic.bundle.min.js:22)(anonymous function) @ ionic.bundle.min.js:150

Error Screenshot :

![screenshot_1](https://cloud.githubusercontent.com/assets/922142/17410993/d0556288-5a93-11e6-8a0c-16a8a5cb11bd.png)

Code of particular function :`

![screenshot_2](https://cloud.githubusercontent.com/assets/922142/17411007/e4e3355e-5a93-11e6-9243-049cbd3c676a.png)

We need your immediate assistance to solve this issue. 
Looking forward for your response.

**Comment by mihui** [comment]
I created both ionic and cordova projects just now and add the plugin, they work well. Is there any customized global variable named "WatsonSDK" in your project? or did you build the project firstly to generate the JavaScript files? Or could you please try to remove the window reference and use WatsonSDK.SpeechToText directly? As I know the $window injection is preferred in the ionic framework instead of window. @andaralex

**Comment by andaralex** [comment]
Hi mihui,

Thanks for the update.

Without using window reference it shows error like "WatsonSDK is not defined". I have tried to add this plugin within the existing developed project.

Even I checked there is no customized object in the application.

I dont know , if i have missed anything in installation and configuration part. If possible could u share the demo ionic application for my reference.

Once again , thanks for your instant reply.

**Comment by andaralex** [comment]
Hi Michael,

We are waiting for sample application.

**Comment by mihui** [comment]
Hi @andaralex , sorry I guess we have a very different timezone, sorry for that.

Please take a look at this repo: https://github.com/CognitiveBuild/WatsonSpeechPluginSample

As there is no issues from my side, I didn't actually create a qualified Sample, but this one should be good enough to prove something you want. 

And there is only one button in green, after you click on it, it will invoke `WatsonSDK.SpeechToText.recognize` without the error you had, but please do not use it in browser because it only supports the mobile device or simulator.

![simulator](https://cloud.githubusercontent.com/assets/1511528/17446386/acd6feb4-5b7b-11e6-94ee-2571171bcf95.png)

**Comment by andaralex** [comment]
Hi Michael, Yes we are in different time zone and thanks for your sample app. We will check it out this sample app today and update you.

**Comment by mihui** [comment]
@andaralex Sure, looking forward to it.

**Comment by andaralex** [comment]
Hi Michael,
Yes its working fine in iPhone.

**Comment by mihui** [comment]
@andaralex thanks, I'm closing this issue now.
